language: python
sudo: required
dist: trusty
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
    # Workaround: use lxml 4.0.0 because 4.1.0 fails on Python 3.2
  - pip install lxml==4.0.0
  - pip install .
    # Coverage >= 4.0 doesn't support Python 3.2
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; else travis_retry pip install coverage; fi
  - travis_retry pip install -e git+https://github.com/codacy/python-codacy-coverage.git#egg=codacy
before_script:
  - sudo ./.travis-setup.sh "$USER" "$BENCHEXEC_TEST_USER"
  - printf 'import coverage\ncoverage.process_startup()\n' > "/home/travis/virtualenv/python${TRAVIS_PYTHON_VERSION}/lib/python${TRAVIS_PYTHON_VERSION}/sitecustomize.py"
env:
  - BENCHEXEC_TEST_USER=benchmarks COVERAGE_PROCESS_START=.coveragerc
script:
  - coverage run setup.py test
after_success:
  - coverage combine
  - coverage report
  - coverage xml
    # Only report test coverage to Codacy for one of the builds (with Python 3.4)
  - if [ ! -z "$CODACY_PROJECT_TOKEN" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.4" ] && [ "$TRAVIS_BRANCH" == "master" ]; then python-codacy-coverage -r coverage.xml; fi
notifications:
  email:
    - benchexec-dev@googlegroups.com
